Improve configure script error message
Review 1908 by @larkost
Closes #2827

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -589,16 +589,24 @@ write_version () {
 
 # test_version_ge <name> <version> <min version>
 test_version_ge () {
+    local fetch_message
     if ! [[ $2 -ge $3 ]]; then
-        error "$1 $(write_version $2) is too old. At least $1 $(write_version $3) is required"
+        if can_fetch "$(bin_pkg_name "$1")"; then
+            fetch_message=" Try running ./configure with --allow-fetch"
+        fi
+        error "$1 $(write_version $2) is too old. At least $1 $(write_version $3) is required.$fetch_message"
         return 1
     fi
 }
 
 # test_version_le <name> <version> <max version>
 test_version_le () {
-    if ! [[ $2 -le $3 ]]; then 
-       error "$1 $(write_version $2) is too recent. At most $1 $(write_version $3) is required"
+    local fetch_message
+    if ! [[ $2 -le $3 ]]; then
+        if can_fetch "$(bin_pkg_name "$1")"; then
+            fetch_message=" Try running ./configure with --allow-fetch"
+        fi
+        error "$1 $(write_version $2) is too recent. At most $1 $(write_version $3) is required.$fetch_message"
         return 1
     fi
 }
