Improve cross-compiling support in configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -55,11 +55,12 @@ configure () {
     require "Use ccache"
     boolvar USE_CCACHE $use_ccache
     check_cxx
-    require "Target System"
-    var MACHINE $($CXX -dumpmachine)
     require "Host System"
+    var MACHINE $($CXX -dumpmachine)
+    require "Build System"
     show "`uname -msr`"
-    require "Target Operating System"
+    check_cross_compiling
+    require "Host Operating System"
     case "${MACHINE#*-}" in
         *apple-darwin*)
             var OS "Darwin"
@@ -74,7 +75,7 @@ configure () {
     esac
     case "${MACHINE%%-*}" in
         x86_64|i?86) true ;;
-        arm) final_warning="ARM support is still experimental";;
+        arm*) final_warning="ARM support is still experimental";;
         *) error "unsopported architecture: $MACHINE"
     esac
     var M_LIBS -lm
@@ -82,7 +83,7 @@ configure () {
     boolvar NO_TCMALLOC not $with_tcmalloc
     require "Build client drivers"
     boolvar BUILD_DRIVERS $enable_drivers
-    require "Host Architecture"
+    require "Build Architecture"
     var GCC_ARCH $(uname -m | grep '^[A-Za-z0-9_]*$' | head -n 1)
     var GCC_ARCH_REDUCED $(echo "$GCC_ARCH" | sed -e 's/^i[56]86$$/i486/g')
     if [ "$COMPILER" = CLANG ]; then
@@ -148,7 +149,7 @@ configure () {
             fetch_pkg $pkg
         fi
     done
-    if [ -n "$final_warning" ]; then
+    if [ -n "${final_warning:-}" ]; then
         echo "* Warning: $final_warning"
     fi
 }
@@ -520,10 +521,10 @@ check_cxx () {
     require "C++ Compiler"
     local force_CXX
     lookup "$force_paths" cxx force_CXX || :
-    local test_CXX=${force_CXX:-${CXX:-c++}}
-    local full_CXX=$(which "$test_CXX" 2>/dev/null)
+    local test_CXX="${force_CXX:-${CXX:-c++}}"
+    local full_CXX="$(which "$test_CXX" 2>/dev/null)"
     if [[ ! -x "$full_CXX" ]]; then
-        if [[ -n ${force_CXX:-} ]]; then
+        if [[ -n "${force_CXX:-}" ]]; then
             error "unable to run $force_CXX"
             return
         fi
@@ -562,7 +563,7 @@ check_cxx () {
 # foo --version | extract_version_string
 # find a version string in the output of foo --version
 extract_version_string () {
-    egrep -o '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n 1
+    sed 's/([^)]*)//g' | egrep -o '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -n 1
 }
 
 # read_version "1.2.3" -> 10203
@@ -893,19 +894,27 @@ check_lib_compile () {
     fi
 }
 
-check_static_lib () {
-    local path=$(static_lib_lookup $1)
-    if [[ -n "$path" ]]; then
-        var_append $(uc $2)_LIBS "$path"
-        var HAS_$(uc $2) 1
+# Test if we are cross-compiling
+check_cross_compiling () {
+    require "Cross-compiling"
+    local bfile="$root/mk/gen/check_cross_compile"
+    echo "int main(){ return 0; }" > "$bfile.cc"
+    if ! "$CXX" ${CXXFLAGS:-} ${LDFLAGS:-} "$bfile.cc" -o "$bfile.out" 1>"$bfile.log" 2>&1; then
+        error_details=$(cat "$bfile.log")
+        error "Failed to compile"
+    else
+        if "$bfile.out" >/dev/null 2>&1; then
+            boolvar CROSS_COMPILING false
+        else
+            boolvar CROSS_COMPILING true
+        fi
     fi
 }
 
-# Find a static library and print it's path
-static_lib_lookup () {
+check_static_lib () {
     for path in $try_lib_paths; do
         local l=$path/lib$1.a
-        test -f $l && echo $l && return 0
+        check_lib_compile "$l" "$2"
     done
 }
 
@@ -941,6 +950,9 @@ niceabspath () {
 test_protobuf () {
     require "Test protobuf"
     if any "protoc protobuf" contains "$FETCH_LIST"; then
+        if [[ -z "${PROTOC_BIN_DEP:-}" ]]; then
+            fetch_bin protoc
+        fi
         show fetch
         return
     fi
