More checks for protobuf in ./configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -123,6 +123,7 @@ configure () {
             check_lib unwind
         fi
     fi
+    test_protobuf
     boolvar STATIC_V8 contains "$static_libs" v8
     var FETCH_LIST "$fetch_list"
     boolvar FETCH_INTERNAL_TOOLS $allow_fetch
@@ -647,15 +648,7 @@ optional_dep () {
 }
 
 # An assoc-list of c++ code to test if a library works
-lib_test_code=':~
-~v8:
-#include <v8.h>
-#include <string>
-int main(){
-  std::string a("foo");
-  v8::String b = v8::String::New(a);
-}
-'
+lib_test_code=':~'
 
 # An assoc-list of possible library aliases
 lib_alias=':~'
@@ -723,9 +716,9 @@ check_dyn_lib () {
 check_lib_compile () {
     local bfile=`dirname $0`/mk/gen/check_$1
     local code
-    if ! lookup "$lib_test_code" $1 code; then
+    # if ! lookup "$lib_test_code" $1 code; then
         code='int main(){}'
-    fi
+    # fi
     echo "$code" > "$bfile.cc"
     if "$CXX" ${CXXFLAGS:-} ${LDFLAGS:-} ${LIB_SEARCH_PATHS:-} "$bfile.cc" -l$1 -o "$bfile.out" 1>"$bfile.log" 2>&1; then
 	var_append LIBRARIES -l$1
@@ -785,6 +778,28 @@ check_coffee_version () {
     else
         show $version
     fi
+}
+
+test_protobuf () {
+    require "Test protobuf"
+    if any "protoc protobuf" contains "$fetch_list"; then
+        show fetch
+        return
+    fi
+    local pbdir=`dirname $0`/mk/gen/protoc/
+    mkdir -p "$pbdir"
+    echo 'message Foo { enum Bar { Baz = 1; } }' > "$pbdir/test.proto"
+    echo 'int main(){ return 0; }' > "$pbdir/main.cc"
+    local out
+    if ! out=$(
+            "$PROTOC" "$pbdir/test.proto" --cpp_out=. 2>&1 &&
+            "$CXX" -lprotobuf -pthread ${CXXFLAGS:-} ${LDFLAGS:-} ${LIB_SEARCH_PATHS:-} "$pbdir/test.pb.cc" "$pbdir/main.cc" 2>&1)
+    then
+        error_details="$out"
+        error "Unable to compile sample protobuf file"
+        return
+    fi
+    show success
 }
 
 # Call the main command with the command line arguments
